title = "Main page"
baseURL = "https://s174508.github.io/SocialData/"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"
contentDir = "content"
publishDir = "docs"
#draft = true #COMMENT THIS OUT WHEN PUBLISHING

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "/images/Github_icon.svg"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[markup.goldmark.renderer]
  unsafe = true